# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a3017507fb70a10154abeb71f2b1fd40e6dfca96f63dbf31b8ab09394523d5fd71f7ce18501e61dde536d28c551d0fa1836e08efb648bf903675a513c31bf9f

test:
  secret_key_base: 34c59c77d86dfdc3cc04bf3dc141e5d97ad05e21708fb7ee1eeec2c4cb4a39a6621a5fac6e33200d3d29c1f65f05f4a4b4ec8e57495a54fdb13f6e20cb9059e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
